config/routes.rb
MyTodo::Application.routes.draw do
  resources :todos do
    resources :tags, only: [:create]
  end

  resources :payments, only: [:new, :create]

  namespace :admin do
    resources :todos, only: [:index]
  end

  root :to => 'todos#index'

  get 'front_page', to: 'pages#front'

  resources :sessions, only: [:create, :destroy]
  get 'sign_out', to: 'sessions#destroy'
end

app/models/stripe_wrapper.rb
module StripeWrapper
 class Charge
   attr_reader :response, :status

   def initialize(response, status)
     @response = response
     @status   = status
   end

   def self.create(options={})
      StripeWrapper.set_api_key
      begin
        response = Stripe::Charge.create(amount: options[:amount],
                                         currency: 'usd',
                                         card: options[:card])
        new(response, :success)
      rescue Stripe::CardError => e
        new(e, :error)
      end
    end

    def successful?
      status == :success
    end

    def error_message
      response.message
    end
  end

    def self.set_api_key
      Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :todos, through: :taggings
  validates_presence_of :name
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :todo
  belongs_to :tag
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  include Tokenable
  has_many :taggings
  has_many :tags, through: :taggings
  validates_presence_of :name
  belongs_to :user

  def name_only?
    description.blank?
  end

  def display_text
    name + tag_text
  end

  def save_with_tags(user)
    self.user = user
    if save
      create_location_tags
      true
    else
      false
    end
  end

  def to_param
    token
  end

  def tag_text
    if tags.any?
      " (" +
      "#{ tags.one? ? 'tag' : 'tags' }: " +
      "#{ tags.map(&:name).first(4).join(", ") }" +
      "#{ ', more...' if tags.count > 4 }" +
      ")"
    else
      ""
    end
  end

private
  def create_location_tags
    location_string = name.slice(/.*\bAT\b(.*)/, 1).try(:strip)
    if location_string
      locations = location_string.split(/\,|and/).map(&:strip)
      locations.each do |location|
        tags.create(name: "location:#{location}")
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
end

app/controllers/admin/todos_controller.rb
class Admin::TodosController < AdminsController
  def index
    @todos = Todo.all
  end
end

app/controllers/admins_controller.rb
class AdminsController < AuthenticatedController
  before_filter :ensure_admin

  def ensure_admin
    unless current_user.admin?
      flash[:error] = 'You do not have access to that area.'
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def require_user
    redirect_to front_page_path unless current_user
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_filter :require_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
    redirect_to todos_path if current_user
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    token = params[:stripeToken]

    charge = StripeWrapper::Charge.create(
      :amount => 3000,
      :card => token,
    )
    if charge.successful?
      flash[:success] = 'Thank you for your generous support.'
      redirect_to new_payment_path
    else
      flash[:error] = charge.error_message
      redirect_to new_payment_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.where(username: params[:username]).first
    if user
      session[:user_id] = user.id
      redirect_to current_user.admin? ? admin_todos_path : todos_path
    else
      flash[:error] = "This application is invite only."
      redirect_to front_page_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @todo = Todo.find(params[:todo_id])
    @tag = @todo.tags.build(tag_params)
    
    if @tag.save
      redirect_to root_path
    else
      render :new
    end
  end

private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/todos_controller.rb
class TodosController < AuthenticatedController

  def index
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save_with_tags(current_user)
      AppMailer.notify_on_new_todo(current_user, @todo).deliver
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @todo = Todo.find_by_token(params[:id])
  end

private
  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitterized_type(type)
    case type
    when :alert
      "alert-block"
    when :error
      "alert-danger"
    when :notice
      "alert-info"
    when :success
      "alert-success"
    else
      type.to_s
    end
  end

  def my_form_for(record, options = {}, &proc)
    form_for(record, options.merge!({builder: MyFormBuilder}), &proc)
  end
end

app/helpers/my_form_builder.rb
class MyFormBuilder < ActionView::Helpers::FormBuilder
  def label(method, text = nil, options = {}, &block)
    errors = object.errors[method.to_sym]
    if errors
      text += " <span class=\"error\">#{errors.first}</span>"
    end
    @template.label(@object_name, method, text.html_safe, objectify_options(options), &block)
  end
end

app/views/admin/todos/index.html.haml
%h1 Todos!
%p
  = 'Hello, ' + current_user.name + ' ( ' 
  = link_to('Sign Out', sign_out_path) 
  = ' )'
%ul
  - @todos.each do |todo|
    %li
      = link_to todo.display_text, todo
      \-
      %span= todo.user.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyTodo
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield :head
  %body.container
    %header
      %h1= link_to 'Todos!', root_path
      = render 'shared/header'
    = yield

app/views/pages/front.html.haml
%h1 Please login

= form_tag sessions_path do
  = label_tag :username
  = text_field_tag :username
  = submit_tag "Sign in", class: "btn"

app/views/payments/new.html.haml
= content_for :head do
  %script(type="text/javascript" src="https://js.stripe.com/v2/")
  :javascript
    Stripe.setPublishableKey('pk_test_4NbXAB02BkDybgtM3SEbKsRN');
  = javascript_include_tag 'payments'
%p Thank you for your support.

= form_tag payments_path, id: 'payment-form' do
  -# %script(src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="pk_test_4NbXAB02BkDybgtM3SEbKsRN" data-amount="3000" data-name="Support todo app" data-description="Thanks you for your donation for todo app")
  %fieldset
    %span.payment-errors
    %label.my_label(for="credit-card-number") Credit Card Number
    %input#credit-card-number.span3.card-number(type='text')
    %label.my_label(for="security-code") Security Code
    %input#security-code.span3.card-cvc(type='text')
    %label.my_label Expiration
    = select_month(Date.today, {add_month_numbers: true}, name: nil, class: 'span2 card-expiry-month')
    = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, name: nil, class: 'span2 card-expiry-year')
  %fieldset.actions
    = submit_tag 'Submit Payments', class: 'btn payment_submit'

app/views/shared/_header.html.haml
- flash.each do |name, msg|
  %div(class="alert #{twitterized_type(name)}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/todos/index.html.haml
%p
  = 'Hello, ' + current_user.name + ' ( ' 
  = link_to('Sign Out', sign_out_path) 
  = ' )'
= my_form_for Todo.new do |f|
  = f.text_field :name
  = f.submit "Add Todo"
%ul
  - @todos.each do |todo|
    %li
      = link_to todo.display_text, todo

= link_to 'Donate', new_payment_path

app/views/todos/new.html.haml
%section.new_todo
  %h3 Add a new todo
  = my_form_for @todo do |f|
    = f.label :name, "Name"
    = f.text_field :name
    %br
    = f.label :description, "Description"
    = f.text_area :description, rows: 6
    %br
    = f.submit "Add This Todo"

app/views/todos/show.html.haml
%p
  %b Name:
  = @todo.name
  %br
  %b Description:
  = @todo.description
  %br
  %b Tag Text:
  = @todo.tag_text
%p= link_to 'All Todos', todos_path